version: "3"

services:
  webserver:
    image: "nginx:stable-alpine"
    container_name: "website_container_test"
    ports:
      - "2222:80"
    volumes:
      - "./dist:/web"
      - "./cauhinhnginx.conf:/etc/nginx/conf.d/default.conf"
  npm:
    image: "node:13"
    container_name: "nodejs_test"
    volumes:
      - "./:/web"
